[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
lockfile = false
pin = true

[tools]
"npm:npm" = "11.7.0" # before node
bun = "1.3.4"
deno = "2.6.0"
"github:jdx/usage" = "2.9.0"
node = "22.21.1"
"npm:@devcontainers/cli" = "0.80.3"
"npm:npm-check" = "6.0.1"
"npm:pnpm" = "10.26.1"
